/**
 * Data workspace icon set — the approved MMSBUILD Data Workbench artwork.
 *
 * GENERATED by `scripts/gen-data-icons.mjs` from the approved screen's
 * vendored `pixel-art-icons` sources. Do not hand-edit; regenerate instead.
 *
 * Why this exists: the repo-wide `pixel-art-icons` vendor was re-skinned to
 * render Remix Icon webfont glyphs (the MMS Design System's icon family for
 * the rest of the admin). The approved Data screen renders the ORIGINAL
 * pixel-art SVG artwork, and the client sign-off is against that artwork — so
 * the Data page carries its own copy of exactly the 48 glyphs it uses.
 *
 * The `IconProps` contract and the `*Icon` export names are identical to the
 * shared set, so call sites differ only in their import specifier.
 */
import type { IconProps } from 'pixel-art-icons/types'

const VIEW_BOX = '0 0 24 24'

export function ArrowDownIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 12h6v2h-2v2h-2v2h-2v2h-2v-2H9v-2H7v-2H5v-2h6V4h2v8Z"/>
    </svg>
  )
}

export function ArrowUpIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 20h2V4h-2zm2-12h2V6h-2zm2 2h2V8h-2zm2 2h2v-2h-2zm-6-4H9V6h2z"/><path d="M15 10H7V8h8zm2 2H5v-2h12z"/>
    </svg>
  )
}

export function ArrowLeftIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M20 11v2H4v-2zM8 13v2H6v-2zm2 2v2H8v-2zm2 2v2h-2v-2zm-4-6V9H6v2z"/><path d="M10 15V7H8v8zm2 2V5h-2v12z"/>
    </svg>
  )
}

export function ArrowRightIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M4 11v2h16v-2zm12 2v2h2v-2zm-2 2v2h2v-2zm-2 2v2h2v-2zm4-6V9h2v2z"/><path d="M14 15V7h2v8zm-2 2V5h2v12z"/>
    </svg>
  )
}

export function BoxSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M14 4h4v2h4v12h-4v2h-4v-8h4v-2h2V8h-2v2h-4v2h-4v-2H6v2h4v2h2v6h2v2h-4v-2H6v-2H2V6h4V4h4V2h4v2ZM4 10h2V8H4v2Z"/>
    </svg>
  )
}

export function BracesIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M6 4h4v2H6zm12 0h-4v2h4zM6 20h4v-2H6zm12 0h-4v-2h4zM4 6h2v5H4zm16 0h-2v5h2zM4 18h2v-5H4zm16 0h-2v-5h2zM2 11h2v2H2zm20 0h-2v2h2z"/>
    </svg>
  )
}

export function BulletlistSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M6 15h2v2H6v2H4v-2H2v-2h2v-2h2v2Zm12 4h-8v-2h8v2Zm4-4H10v-2h12v2ZM6 7h2v2H6v2H4V9H2V7h2V5h2v2Zm12 4h-8V9h8v2Zm4-4H10V5h12v2Z"/>
    </svg>
  )
}

export function CalendarSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M17 4h2v2h2v14h-2v2H5v-2H3V6h2V4h2V2h2v2h6V2h2v2ZM5 10h14V8H5v2Z"/>
    </svg>
  )
}

export function CheckIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M10 18H8v-2h2v2Zm-2-2H6v-2h2v2Zm4-2v2h-2v-2h2Zm-6 0H4v-2h2v2Zm8 0h-2v-2h2v2Zm2-2h-2v-2h2v2Zm2-2h-2V8h2v2Zm2-2h-2V6h2v2Z"/>
    </svg>
  )
}

export function ChevronDownIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 16h-2v-2h2v2Zm-2-2H9v-2h2v2Zm4 0h-2v-2h2v2Zm-6-2H7v-2h2v2Zm8 0h-2v-2h2v2ZM7 10H5V8h2v2Zm12 0h-2V8h2v2Z"/>
    </svg>
  )
}

export function ChevronUpIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 8h-2v2h2V8Zm-2 2H9v2h2v-2Zm4 0h-2v2h2v-2Zm-6 2H7v2h2v-2Zm8 0h-2v2h2v-2ZM7 14H5v2h2v-2Zm12 0h-2v2h2v-2Z"/>
    </svg>
  )
}

export function CircleAlertSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M18 4h2v2h2v12h-2v2h-2v2H6v-2H4v-2H2V6h2V4h2V2h12v2Zm-7 14h2v-2h-2v2Zm0-4h2V6h-2v8Z"/>
    </svg>
  )
}

export function CloseIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M7 19H5v-2h2v2Zm12 0h-2v-2h2v2ZM9 15v2H7v-2h2Zm8 2h-2v-2h2v2Zm-6-2H9v-2h2v2Zm4 0h-2v-2h2v2Zm-2-2h-2v-2h2v2Zm-2-2H9V9h2v2Zm4 0h-2V9h2v2ZM9 9H7V7h2v2Zm8 0h-2V7h2v2ZM7 7H5V5h2v2Zm12 0h-2V5h2v2Z"/>
    </svg>
  )
}

export function CopySolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M20 8h2v12h-2v2H8v-2H6V8h2V6h12v2ZM4 16H2V4h2v12ZM16 4H4V2h12v2Z"/>
    </svg>
  )
}

export function CornerDownLeftIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M10 20H8v-2H6v-2H4v-2h2v-2h2v-2h2v4h8v2h-8v4Zm10-6h-2V4h2v10Z"/>
    </svg>
  )
}

export function DatabaseSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M16 20v2H8v-2h8Zm-8 0H4v-2h4v2Zm12 0h-4v-2h4v2ZM4 18H2v-2h2v2Zm12 0H8v-2h8v2Zm6 0h-2v-2h2v2ZM8 16H4v-2h4v2Zm12 0h-4v-2h4v2ZM4 14H2v-2h2v2ZM16 4h4v2h2v4h-2v2h-4v2H8v-2H4v-2H2V6h2V4h4V2h8v2Zm6 10h-2v-2h2v2Z"/>
    </svg>
  )
}

export function EditSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M14 10h2v4h-2v2h-2v2h-2v2H8v2H2v-6h2v-2h2v-2h2v-2h2V8h4v2Zm4-6h2v2h2v2h-2v2h-4V8h-2V4h2V2h2v2Z"/>
    </svg>
  )
}

export function ExternalLinkSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 9H9v2H7v6h6v-2h2v-2h4v6h-2v2H5v-2H3V7h2V5h6v4Zm0 6H9v-2h2v2Zm2-2h-2v-2h2v2Zm2-2h-2V9h2v2Zm6 0h-2V7h-2V5h-4V3h8v8Zm-4-2h-2V7h2v2Z"/>
    </svg>
  )
}

export function FileTextSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M16 4h-2v4h4V6h2v14h-2v2H6v-2H4V4h2V2h10v2ZM8 18h8v-2H8v2Zm0-4h8v-2H8v2Zm0-4h2V8H8v2Zm10-4h-2V4h2v2Z"/>
    </svg>
  )
}

export function FolderGlyphIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M12 6h10v14H2V4h10v2Z"/>
    </svg>
  )
}

export function Grid2x22SolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 22H4v-2H2v-7h9v9Zm11-2h-2v2h-7v-9h9v7Zm-11-9H2V4h2V2h7v9Zm9-7h2v7h-9V2h7v2Z"/>
    </svg>
  )
}

export function ImageSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M20 22H4v-2H2V4h2V2h16v2h2v16h-2v-6h-2v-2h-2v2h-2v2h-2v-2h-2v2H8v2H6v2h10v-2h2v2h2v2Zm-4-4h-2v-2h2v2ZM8 8H6v2h2v2h2v-2h2V8h-2V6H8v2Z"/>
    </svg>
  )
}

export function ImageXSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M14 10h8v10h-2v2H4v-2H2V4h2V2h10v8Zm2 4h-2v2h2v2h-2v-2h-2v-2h-2v2H8v2H6v2h10v-2h2v2h2v-6h-2v-2h-2v2ZM8 8H6v2h2v2h2v-2h2V8h-2V6H8v2Zm10 0h-2V6h2v2Zm4 0h-2V6h2v2Zm-2-2h-2V4h2v2Zm-2-2h-2V2h2v2Zm4 0h-2V2h2v2Z"/>
    </svg>
  )
}

export function LayoutSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M8 20H4v-2H2v-8h6v10Zm14-2h-2v2H10V10h12v8ZM20 6h2v2H2V6h2V4h16v2Z"/>
    </svg>
  )
}

export function LinkIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 18H4v-2h7v2Zm9 0h-7v-2h7v2ZM4 16H2V8h2v8Zm18 0h-2V8h2v8Zm-5-3H7v-2h10v2Zm-6-5H4V6h7v2Zm9 0h-7V6h7v2Z"/>
    </svg>
  )
}

export function ListBoxSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M20 4h2v16h-2v2H4v-2H2V4h2V2h16v2ZM6 17h2v-2H6v2Zm4 0h8v-2h-8v2Zm-4-4h2v-2H6v2Zm4 0h8v-2h-8v2ZM6 9h2V7H6v2Zm4 0h8V7h-8v2Z"/>
    </svg>
  )
}

export function LoaderIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 22h-2v-6h2v6Zm-6-3H5v-2h2v2Zm12 0h-2v-2h2v2ZM9 17H7v-2h2v2Zm8 0h-2v-2h2v2Zm-9-4H2v-2h6v2Zm14 0h-6v-2h6v2ZM9 9H7V7h2v2Zm8 0h-2V7h2v2Zm-4-1h-2V2h2v6ZM7 7H5V5h2v2Zm12 0h-2V5h2v2Z"/>
    </svg>
  )
}

export function LockSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M9 8h6V4h2v4h2v2h2v10h-2v2H5v-2H3V10h2V8h2V4h2v4Zm6-4H9V2h6v2Z"/>
    </svg>
  )
}

export function MoreVerticalSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 23h-2v-2H9v-2h2v-2h2v2h2v2h-2v2Zm0-12h2v2h-2v2h-2v-2H9v-2h2V9h2v2Zm0-8h2v2h-2v2h-2V5H9V3h2V1h2v2Z"/>
    </svg>
  )
}

export function OpenSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 9H9v2H7v6h6v-2h2v-2h4v6h-2v2H5v-2H3V7h2V5h6v4Zm0 4v2H9v-2h2Zm2 0h-2v-2h2v2Zm2-2h-2V9h2v2Zm6 0h-2V7h-2V5h-4V3h8v8Zm-4-2h-2V7h2v2Z"/>
    </svg>
  )
}

export function PlusIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 11h7v2h-7v7h-2v-7H4v-2h7V4h2v7Z"/>
    </svg>
  )
}

export function ReloadIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M10 16h10v2H10v4H8v-2H6v-2H4v-2h2v-2h2v-2h2v4Zm12 0h-2v-5h2v5ZM4 13H2V8h2v5Zm12-9h2v2h2v2h-2v2h-2v2h-2V8H4V6h10V2h2v2Z"/>
    </svg>
  )
}

export function SaveSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M18 4h2v2h2v14h-2v2H4v-2H2V4h2V2h14v2ZM6 14v6h2v-6H6Zm10 0v6h2v-6h-2Zm-8-2v2h8v-2H8ZM6 6v4h6V6H6Z"/>
    </svg>
  )
}

export function SearchSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M22 22h-2v-2h2v2Zm-2-2h-2v-2h2v2Zm-6-2H6v-2H4v-2H2V6h2v4h2V6h4V4H6V2h8v2h2v2h2v8h-2v2h-2v2Zm4 0h-2v-2h2v2ZM6 6H4V4h2v2Z"/>
    </svg>
  )
}

export function SendSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M8 5h4v2h4v2h4v2h2v2h-2v2h-4v2h-4v2H8v2H2v-8h4v-2H2V3h6v2Z"/>
    </svg>
  )
}

export function Settings2SolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M10 14h2v2h10v2H12v2h-2v2H6v-2H4v-2H2v-2h2v-2h2v-2h4v2Zm8-10h2v2h2v2h-2v2h-2v2h-4v-2h-2V8H2V6h10V4h2V2h4v2Z"/>
    </svg>
  )
}

export function StarSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M13 3h2v4h8v4h-2v2h-2v3h2v6h-5v-2h-2v-2h-4v2H8v2H3v-6h2v-3H3v-2H1V7h8V3h2V1h2v2Z"/>
    </svg>
  )
}

export function TargetSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M19 23H5v-2H3v-2H1V5h2V3h2V1h14v2h2v2h2v14h-2v2h-2v2ZM9 19h6v-2H9v2Zm-2-2h2v-2H7v2Zm8 0h2v-2h-2v2ZM5 15h2V9H5v6Zm6 0h2v-2h-2v2Zm6 0h2V9h-2v6Zm-8-2h2v-2H9v2Zm4 0h2v-2h-2v2Zm-2-2h2V9h-2v2ZM7 9h2V7H7v2Zm8 0h2V7h-2v2ZM9 7h6V5H9v2Z"/>
    </svg>
  )
}

export function TrashSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M18 22H6V20H4V10H20V20H18V22ZM9 6H15V4H17V6H22V8H2V6H7V4H9V6ZM15 4H9V2H15V4Z"/>
    </svg>
  )
}

export function UploadIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M19 21H5v-2h14v2ZM5 19H3v-4h2v4Zm16 0h-2v-4h2v4ZM13 5h2v2h2v2h-4v8h-2V9H7V7h2V5h2V3h2v2Z"/>
    </svg>
  )
}

export function UsersSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M12 16h2v2h2v4H0v-4h2v-2h2v-2h8v2Zm10 2h2v4h-6v-6h-2v-2h4v2h2v2ZM11 4h2v6h-2v2H5v-2H3V4h2V2h6v2Zm8 0h2v6h-2v2h-4V2h4v2Z"/>
    </svg>
  )
}

export function VideoSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M16 19H4v-2H2V7h2V5h12v2h2v2h2V7h2v10h-2v-2h-2v2h-2v2Z"/>
    </svg>
  )
}

export function BoxStackSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M6 7h4v2h4V7h4V5h4v14h-4v2h-4v-6h4v-2h2v-2h-2v2h-4v2h-4v-2H6v2h4v2h2v4h2v2h-4v-2H6v-2H2V5h4v2Zm-2 6h2v-2H4v2Zm6-10V1h4v2h4v2h-4v2h-4V5H6V3h4Z"/>
    </svg>
  )
}

export function CheckboxSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M20 4h2v16h-2v2H4v-2H2V4h2V2h16v2Z"/>
    </svg>
  )
}

export function HeadingIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M7 11h10V4h2v16h-2v-7H7v7H5V4h2v7Z"/>
    </svg>
  )
}

export function RulerDimensionSolidIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M19 13h2v6h-2v2H5v-2H3v-6h2v-2h14v2ZM7 16h2v-3H7v3Zm4 0h2v-3h-2v3Zm4 0h2v-3h-2v3ZM5 5h14V3h2v6h-2V7H5v2H3V3h2v2Z"/>
    </svg>
  )
}

export function TextColumsIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M11 19H3v-2h8v2Zm10 0h-8v-2h8v2Zm-10-4H3v-2h8v2Zm10 0h-8v-2h8v2Zm-10-4H3V9h8v2Zm10 0h-8V9h8v2ZM11 7H3V5h8v2Zm10 0h-8V5h8v2Z"/>
    </svg>
  )
}

export function TextStartTIcon({ size = 24, color = 'currentColor', className, style }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox={VIEW_BOX}
      fill={color}
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
    >
      <path d="M22 20H2v-2h20v2Zm0-4H2v-2h20v2Zm0-4H12v-2h10v2ZM10 8H8V6H7v4h2v2H3v-2h2V6H4v2H2V4h8v4Zm12 0H12V6h10v2Z"/>
    </svg>
  )
}
