// Operator console administrators (R14), each scoped to the platform, one
// Operator or one Business (R1). Only the scrypt hash is stored. A password is
// either generated by the CLI (registry/adminCreate.mjs) and shown once, or set
// by the person through a one-time invite from the console.
import { query } from './db.mjs';
import { hashPassword, verifyPassword, genInviteToken, hashToken } from '../lib/crypto.mjs';
import { scopeOf, canManageAdmin } from '../lib/scope.mjs';
import { getBusiness } from './org.mjs';

const normEmail = (email) => String(email || '').trim().toLowerCase();

const COLUMNS = 'id, email, status, scope_level, operator_id, business_id, updated_at, created_at, last_login_at';

// Checked against when the email is unknown, so a miss costs the same scrypt
// work as a hit and the response time does not say which emails exist.
const DUMMY_HASH = hashPassword('not-a-real-password');

const status = (msg, code) => Object.assign(new Error(msg), { status: code });

function scopeColumns(scope) {
  const s = scope ?? { level: 'platform' };
  return [
    s.level,
    s.level === 'operator' ? s.operatorId : null,
    s.level === 'business' ? s.businessId : null,
  ];
}

/**
 * Create the admin, or reset the password of an existing one. Bumping
 * `updated_at` is what ends every session signed before the reset. `scope`
 * is applied to a new admin and, when given, to an existing one.
 */
export async function upsertAdmin(email, password, scope = null) {
  const e = normEmail(email);
  if (!e || !e.includes('@')) throw new Error('A valid email is required');
  const [level, opId, bizId] = scopeColumns(scope);
  const { rows } = await query(
    `insert into siteagent_control.admin_users
       (email, password_hash, status, scope_level, operator_id, business_id)
     values ($1, $2, 'active', $3, $4, $5)
     on conflict (email) do update set
       password_hash = excluded.password_hash,
       status = 'active',
       invite_token_hash = null,
       scope_level = case when $6 then excluded.scope_level else siteagent_control.admin_users.scope_level end,
       operator_id = case when $6 then excluded.operator_id else siteagent_control.admin_users.operator_id end,
       business_id = case when $6 then excluded.business_id else siteagent_control.admin_users.business_id end,
       updated_at = now()
     returning ${COLUMNS}`,
    [e, hashPassword(password), level, opId, bizId, scope !== null],
  );
  return rows[0];
}

export async function disableAdminByEmail(email) {
  const { rows } = await query(
    `update siteagent_control.admin_users
        set status = 'disabled', invite_token_hash = null, updated_at = now()
      where email = $1
      returning ${COLUMNS}`,
    [normEmail(email)],
  );
  return rows[0] || null;
}

/** The admin behind a session, or null once they are disabled or gone. */
export async function findActiveAdmin(id) {
  if (!/^\d+$/.test(String(id ?? ''))) return null;
  const { rows } = await query(
    `select ${COLUMNS} from siteagent_control.admin_users where id = $1 and status = 'active'`,
    [String(id)],
  );
  return rows[0] || null;
}

/** The signed-in admin for a correct email + password, else null. */
export async function validateAdminLogin(email, password) {
  const e = normEmail(email);
  if (!e || !password) return null;
  const { rows } = await query(
    `select ${COLUMNS}, password_hash from siteagent_control.admin_users
      where email = $1 and status = 'active' and password_hash is not null`,
    [e],
  );
  const admin = rows[0];
  const ok = verifyPassword(password, admin ? admin.password_hash : DUMMY_HASH);
  if (!admin || !ok) return null;
  await query('update siteagent_control.admin_users set last_login_at = now() where id = $1', [admin.id]);
  const { password_hash, ...rest } = admin;
  return rest;
}

// ---- Console-managed administrators ------------------------------------------

async function businessOf(row) {
  return row.scope_level === 'business' ? getBusiness(row.business_id) : null;
}

/** Administrators the caller may see: at or below its own scope. */
export async function listAdmins(callerScope) {
  const { rows } = await query(
    `select a.${COLUMNS.split(', ').join(', a.')},
            o.name as operator_name, b.name as business_name,
            a.invite_token_hash is not null as invite_pending
       from siteagent_control.admin_users a
       left join siteagent_control.operators o on o.id = a.operator_id
       left join siteagent_control.businesses b on b.id = a.business_id
      where a.status <> 'disabled'
      order by a.scope_level, a.email`,
  );
  const out = [];
  for (const r of rows) {
    if (canManageAdmin(callerScope, r, await businessOf(r))) out.push(r);
  }
  return out;
}

/**
 * Invite an administrator at `targetScope`, which must be at or below the
 * caller's. Returns { admin, token }; the token is shared once.
 */
export async function inviteAdmin(callerScope, email, targetScope) {
  const e = normEmail(email);
  if (!e || !e.includes('@')) throw status('A valid email is required', 400);
  const target = scopeOf({
    scope_level: targetScope.level,
    operator_id: targetScope.operatorId,
    business_id: targetScope.businessId,
  });
  const targetRow = { scope_level: target.level, operator_id: target.operatorId, business_id: target.businessId };
  if (!canManageAdmin(callerScope, targetRow, await businessOf(targetRow))) {
    throw status('You cannot grant access at that level', 403);
  }
  const { rows: existing } = await query('select status from siteagent_control.admin_users where email = $1', [e]);
  if (existing[0] && existing[0].status !== 'invited') {
    throw status('That email already has a console account', 409);
  }
  const token = genInviteToken();
  const [level, opId, bizId] = scopeColumns(target);
  const { rows } = await query(
    `insert into siteagent_control.admin_users
       (email, password_hash, status, scope_level, operator_id, business_id, invite_token_hash)
     values ($1, null, 'invited', $2, $3, $4, $5)
     on conflict (email) do update set
       scope_level = excluded.scope_level, operator_id = excluded.operator_id,
       business_id = excluded.business_id, invite_token_hash = excluded.invite_token_hash,
       updated_at = now()
     where siteagent_control.admin_users.status = 'invited'
     returning ${COLUMNS}`,
    [e, level, opId, bizId, hashToken(`admin:${token}`)],
  );
  if (!rows[0]) throw status('That email already has a console account', 409);
  return { admin: rows[0], token };
}

/** Accept an administrator invite: set the password, activate. */
export async function acceptAdminInvite(token, password) {
  if (!token || !password) return null;
  const { rows } = await query(
    `update siteagent_control.admin_users
        set password_hash = $2, status = 'active', invite_token_hash = null, updated_at = now()
      where invite_token_hash = $1 and status = 'invited'
      returning ${COLUMNS}`,
    [hashToken(`admin:${token}`), hashPassword(password)],
  );
  return rows[0] || null;
}

/** Disable an administrator the caller may manage (never itself). */
export async function disableAdmin(callerScope, callerId, id) {
  if (String(callerId) === String(id)) throw status('You cannot disable your own account', 409);
  const { rows } = await query(`select ${COLUMNS} from siteagent_control.admin_users where id = $1`, [String(id)]);
  const row = rows[0];
  if (!row || row.status === 'disabled' || !canManageAdmin(callerScope, row, await businessOf(row))) {
    throw status('not found', 404);
  }
  const { rows: out } = await query(
    `update siteagent_control.admin_users
        set status = 'disabled', invite_token_hash = null, updated_at = now()
      where id = $1 returning ${COLUMNS}`,
    [row.id],
  );
  return out[0];
}
