// Operator console administrators (R14). Only the scrypt hash is stored; the
// password is generated by the CLI (registry/adminCreate.mjs) and shown once.
import { query } from './db.mjs';
import { hashPassword, verifyPassword } from '../lib/crypto.mjs';

const normEmail = (email) => String(email || '').trim().toLowerCase();

// Checked against when the email is unknown, so a miss costs the same scrypt
// work as a hit and the response time does not say which emails exist.
const DUMMY_HASH = hashPassword('not-a-real-password');

/**
 * Create the admin, or reset the password of an existing one. Bumping
 * `updated_at` is what ends every session signed before the reset.
 */
export async function upsertAdmin(email, password) {
  const e = normEmail(email);
  if (!e || !e.includes('@')) throw new Error('A valid email is required');
  const { rows } = await query(
    `insert into siteagent_control.admin_users (email, password_hash, status)
     values ($1, $2, 'active')
     on conflict (email) do update set
       password_hash = excluded.password_hash,
       status = 'active',
       updated_at = now()
     returning id, email, status, updated_at`,
    [e, hashPassword(password)],
  );
  return rows[0];
}

export async function disableAdmin(email) {
  const { rows } = await query(
    `update siteagent_control.admin_users
        set status = 'disabled', updated_at = now()
      where email = $1
      returning id, email, status`,
    [normEmail(email)],
  );
  return rows[0] || null;
}

/** The admin behind a session, or null once they are disabled or gone. */
export async function findActiveAdmin(id) {
  if (!Number.isSafeInteger(Number(id))) return null;
  const { rows } = await query(
    `select id, email, updated_at from siteagent_control.admin_users
      where id = $1 and status = 'active'`,
    [Number(id)],
  );
  return rows[0] || null;
}

/** The signed-in admin for a correct email + password, else null. */
export async function validateAdminLogin(email, password) {
  const e = normEmail(email);
  if (!e || !password) return null;
  const { rows } = await query(
    `select id, email, password_hash, updated_at from siteagent_control.admin_users
      where email = $1 and status = 'active'`,
    [e],
  );
  const admin = rows[0];
  const ok = verifyPassword(password, admin ? admin.password_hash : DUMMY_HASH);
  if (!admin || !ok) return null;
  await query('update siteagent_control.admin_users set last_login_at = now() where id = $1', [admin.id]);
  return { id: admin.id, email: admin.email, updated_at: admin.updated_at };
}
