// SiteAgent control-plane HTTP API. Node built-ins + pg only.
// Wires Registry + Provisioner + Deployer + AI Gateway. The Astro console calls this.
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { networkInterfaces } from 'node:os';
import { dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './lib/env.mjs';
import { migrate } from './registry/db.mjs';
import { getSettings, saveSettings, getSecrets, getDefaultGuidance, saveDefaultGuidance } from './registry/settings.mjs';
import * as tenantsRepo from './registry/tenants.mjs';
import { provisionTenant, deprovisionTenant, startTenant, resumeAll, editTenant, repairTenantCf, pointTestFunnel } from './provisioner/provision.mjs';
import { deployTenant, hasBakedOutput } from './deployer/deploy.mjs';
import { handleGateway } from './ai-gateway/gateway.mjs';
import { verifyTenantToken, verifyForTenant, decrypt } from './lib/crypto.mjs';
import {
  currentAdmin, isAdminApiPath, connectorMayCall, tokenMatches, signAdminSession,
  loginLockedFor, recordLoginFailure, clearLoginFailures, ADMIN_SESSION_TTL_SEC,
} from './lib/adminAuth.mjs';
import { validateAdminLogin } from './registry/adminUsers.mjs';
import { verifyPersonPassword } from './registry/tenantUsers.mjs';
import { getBusinessInScope, getOperatorInScope, connectorBusiness } from './registry/org.mjs';
import { handleOrgApi, requirePlatform } from './api/orgApi.mjs';
import { handleActAsApi, requireOpenWork, actorPair } from './api/actAsApi.mjs';
import { recordAdminAction, listAdminAudit } from './registry/adminAudit.mjs';
import { sweepExpiredGrants, activeGrants } from './registry/actAs.mjs';
import { brandForScope, productName } from './lib/brand.mjs';
import { syncPeopleSoon } from './provisioner/peopleSync.mjs';
import { isPlatform } from './lib/scope.mjs';
import { decorate } from './lib/tenantView.mjs';
import * as rt from './runtime/tenantRuntime.mjs';
import * as odrt from './runtime/odRuntime.mjs';
import { handleHub } from './hub/hub.mjs';
import { handleMcpGateway } from './mcp/gateway.mjs';
import * as mcpAgents from './registry/mcpAgents.mjs';
import { normalizePermissions, normalizeTables, PERMISSION_PRESETS } from './mcp/permissions.mjs';
import { pluginInstalled } from './mcp/session.mjs';
import { installBridge } from './mcp/bridgeInstall.mjs';
import { serveMcpDocumentation } from './mcp/documentation.mjs';
import { handleGatewayProxy, handleGatewayUpgrade } from './gateway/proxy.mjs';
import { openFunnel, closeFunnel } from './gateway/funnel.mjs';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function send(res, code, obj) {
  res.writeHead(code, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store', ...CORS });
  res.end(JSON.stringify(obj));
}

// The delivery board, generated by `node docs/board/build-board.mjs`.
const BOARD_FILE = resolvePath(dirname(fileURLToPath(import.meta.url)), '../../docs/board/index.html');

/**
 * The board is read by the other party over the tailnet, so it is served with
 * no session — but only to a request that arrived on the tailnet interface. The
 * board names which security controls do not exist yet, which is precisely the
 * list that must not be reachable from the public address.
 *
 * Loopback does NOT count: the Tailscale funnel delivers public traffic to the
 * main server over 127.0.0.1, which is how the board used to be public at
 * <gateway>/board. It is now served only by the tailnet listener at the bottom
 * of this file.
 */
function onPrivateInterface(req) {
  const ip = (req.socket?.localAddress ?? '').replace(/^::ffff:/, '');
  const [a, b] = ip.split('.').map(Number);
  return a === 100 && b >= 64 && b <= 127; // Tailscale's CGNAT range
}

/** This machine's tailnet address, or null when it is not on one. */
function tailnetAddress() {
  for (const list of Object.values(networkInterfaces())) {
    for (const nic of list ?? []) {
      if (nic.family !== 'IPv4' || nic.internal) continue;
      const [a, b] = nic.address.split('.').map(Number);
      if (a === 100 && b >= 64 && b <= 127) return nic.address;
    }
  }
  return null;
}

async function serveBoard(req, res, method) {
  if (method !== 'GET' && method !== 'HEAD') return send(res, 405, { error: 'Use GET.' });
  if (!onPrivateInterface(req)) return send(res, 404, { error: 'Not found.' });
  try {
    const html = await readFile(BOARD_FILE, 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    return res.end(method === 'HEAD' ? undefined : html);
  } catch {
    return send(res, 503, { error: 'The board has not been generated: run node docs/board/build-board.mjs' });
  }
}

function readJson(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => { data += c; if (data.length > 1_000_000) req.destroy(); });
    req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { resolve({}); } });
    req.on('error', () => resolve({}));
  });
}

// A tenant row plus its live runtime status, for the console (lib/tenantView.mjs).
const tenantView = (row) => decorate(row, {
  running: rt.isRunning(row.slug),
  odRunning: odrt.isRunning(row.slug),
  // What to SAY about the studio, rather than merely whether we spawned it
  // (R16). `isRunning` is true from the instant spawn() returns, so it cannot
  // tell a daemon that is listening from one that is three minutes into a boot
  // — and the console rendered neither of those, it rendered the CMS's state.
  // In-process lookups only: probing each row on a listing would open an owner
  // session inside every project, which R5 forbids.
  studio: odrt.studioStatus(row.slug, row.od_port),
  published: hasBakedOutput(row.slug),
});

// The Operator or Business an administrator is scoped to, by name (console header).
async function scopeName(scope) {
  if (scope?.level === 'operator') return (await getOperatorInScope(scope, scope.operatorId))?.name ?? null;
  if (scope?.level === 'business') return (await getBusinessInScope(scope, scope.businessId))?.name ?? null;
  return null;
}

// The session is returned in the body, not as a Set-Cookie: the Astro console
// calls this server-side and sets `sa_admin` on its own /operator path.
async function adminLogin(req, res) {
  const b = await readJson(req);
  const email = String(b.email || '').trim().toLowerCase();
  const lockedMs = loginLockedFor(email);
  if (lockedMs) {
    return send(res, 429, {
      error: `Too many failed sign-ins. Try again in ${Math.ceil(lockedMs / 60_000)} minute(s).`,
      locked: true,
    });
  }
  const admin = await validateAdminLogin(email, String(b.password || ''));
  if (!admin) {
    recordLoginFailure(email);
    // Recorded with the address that was tried, so a run of failures against
    // one account is visible rather than only rate-limited.
    recordAdminAction({
      admin: { id: null, email: email || 'unknown', scope_level: 'unknown' },
      action: 'admin.login.failed', ok: false, ip: req.socket?.remoteAddress ?? null,
    });
    return send(res, 401, { error: 'Wrong email or password.' });
  }
  clearLoginFailures(email);
  recordAdminAction({ admin, action: 'admin.login', ip: req.socket?.remoteAddress ?? null });
  return send(res, 200, {
    session: signAdminSession(admin),
    maxAgeSec: ADMIN_SESSION_TTL_SEC,
    email: admin.email,
  });
}

// Live OpenRouter model catalogue for the console picker, fetched with the
// operator's key. Returns [] until a key is saved (or on any upstream error) so
// the settings page still renders — it just shows no options yet.
async function listOpenrouterModels() {
  const { openrouterKey } = await getSecrets();
  if (!openrouterKey) return [];
  try {
    const r = await fetch('https://openrouter.ai/api/v1/models', {
      headers: { Authorization: `Bearer ${openrouterKey}` },
    });
    if (!r.ok) return [];
    const data = await r.json();
    return (data.data || [])
      .map((m) => ({
        id: m.id,
        name: m.name || m.id,
        // Tool-calling capability for the category picker (Codex #4). OpenRouter
        // lists it in supported_parameters; null = unknown metadata (UI warns
        // instead of hard-blocking). Routed chat categories need this true.
        toolCalling: Array.isArray(m.supported_parameters)
          ? m.supported_parameters.includes('tools')
          : null,
        // Image input capability. The CMS can route around a text-only model
        // (requiresVision -> the Design category), but MMS Design runs on ONE
        // model, so a text-only pick there means every tenant screenshot
        // attachment fails. null = unknown metadata (the picker keeps it).
        vision: m.architecture && Array.isArray(m.architecture.input_modalities)
          ? m.architecture.input_modalities.includes('image')
          : null,
      }))
      .sort((a, b) => a.id.localeCompare(b.id));
  } catch {
    return [];
  }
}

// Reject categories whose model is KNOWN to lack tool-calling (routed chat
// categories always send tools) — server-side enforcement (Codex R2-#1). Models
// with unknown capability are allowed (the UI warns).
// Also covers the MMS Design model, which needs tool-calling even more than the
// CMS categories do: an OpenDesign run is one long tool loop, so a model without
// tools produces a session that talks but never builds anything.
//
// When the catalogue cannot be loaded this REFUSES rather than waving the save
// through (R8, AC-B8.3). It used to do the opposite, on the reasoning that an
// unverifiable claim should not block — but that is precisely a check reporting
// a pass because it could not run, which principle P2 forbids. Refusing costs a
// settings save until the key or the upstream is back; allowing costs a project
// whose design agent can talk and never build, discovered much later.
async function enforceToolCapability({ aiCategories, designModel } = {}) {
  const needs = [];
  if (Array.isArray(aiCategories)) {
    for (const c of aiCategories) {
      if (c && typeof c === 'object' && c.modelId) {
        needs.push({ model: c.modelId, label: `category "${c.slug || c.name}"` });
      }
    }
  }
  if (typeof designModel === 'string' && designModel.trim()) {
    needs.push({ model: designModel.trim(), label: 'MMS Design' });
  }
  if (!needs.length) return;
  const models = await listOpenrouterModels();
  if (!models.length) {
    throw new Error(
      'the model catalogue could not be read, so tool-calling support cannot be checked. '
      + 'Add or fix the OpenRouter key and try again',
    );
  }
  const cap = new Map(models.map((m) => [m.id, m.toolCalling]));
  for (const n of needs) {
    if (cap.get(n.model) === false) {
      throw new Error(`model "${n.model}" for ${n.label} does not support tool calling`);
    }
  }
}

const server = http.createServer(async (req, res) => {
  const path = new URL(req.url, 'http://x').pathname;
  const method = req.method;

  if (method === 'OPTIONS') { res.writeHead(204, CORS); return res.end(); }

  // AI gateway (instances call this; the key never leaves the control plane)
  if (path.startsWith('/ai/')) return handleGateway(req, res, path.slice(4));

  try {
    // MCP gateway (external AI agents). Mounted ahead of the hub and the tenant
    // proxy: it authenticates with its own bearer key, not a hub session, so it
    // must never fall through to either.
    if (path.startsWith('/mcp/') && (await handleMcpGateway(req, res, method, path))) return;

    // MCP guide. Ahead of the gateway proxy, which would otherwise hand every
    // /operator/* path to the Astro console.
    if (await serveMcpDocumentation(req, res, method, path)) return;

    // Tenant Hub (login / invite / two-card home) — the HTML surface tenants use.
    if (await handleHub(req, res, method, path)) return;

    // No /board here: this server is the funnel's upstream, so it is public.
    // The board is served by the tailnet-only listener at the bottom.

    // R14: every admin/operator route requires a signed-in administrator. One
    // gate for all of them, ahead of every handler, so a route cannot forget
    // it (lib/adminAuth.selftest.mjs checks each /api/ route is covered).
    // Phase 1: the administrator (and so their scope — platform, one Operator
    // or one Business) is carried into every handler below.
    let admin = null;
    let viaConnector = false;
    if (isAdminApiPath(path)) {
      admin = await currentAdmin(req);
      viaConnector = !admin && connectorMayCall(method, path, req);
      if (!admin && !viaConnector) {
        return send(res, 401, { error: 'admin sign-in required' });
      }
    }
    const scope = admin?.scope ?? null;

    if (path === '/api/admin/login' && method === 'POST') return adminLogin(req, res);
    if (path === '/api/admin/session' && method === 'GET') {
      // The console asks this on every page, so it carries what every page
      // needs: who you are, the brand this administrator's console wears (R5),
      // and whether you are currently inside somebody's work.
      const brand = await brandForScope(scope);
      // Only a platform administrator can hold a grant, so nobody else pays for
      // the lookup — this route answers every page the console renders.
      const grants = isPlatform(scope) ? await activeGrants(admin?.id) : [];
      const grant = grants[0] || null;
      return send(res, 200, {
        admin: { ...admin, scopeName: await scopeName(scope) },
        brand: brand.isPlatform ? null : {
          name: brand.name,
          logoLight: brand.logoLight,
          logoDark: brand.logoDark,
          accent: brand.accent,
          console: productName(brand, 'console'),
        },
        acting: grant
          ? { slug: grant.tenant_slug, project: grant.project_name || grant.tenant_slug, business: grant.business_name || null }
          : null,
      });
    }

    // Step-up for portal people (NEW-3b). A project's CMS asks whether this is
    // the person's hub password; the request is signed with that project's key,
    // so a project can only ask about its own people.
    if (path === '/internal/hub/verify-password' && method === 'POST') {
      const b = await readJson(req);
      const project = String(b.project || '');
      const claim = /^[a-z0-9-]+$/.test(project) ? verifyForTenant(project, String(b.token || '')) : null;
      if (!claim || claim.kind !== 'hub-verify' || !/^\d+$/.test(String(claim.personId ?? ''))) {
        return send(res, 401, { error: 'unauthorized' });
      }
      const key = `hub:${project}:${claim.personId}`;
      if (loginLockedFor(key)) return send(res, 429, { ok: false, locked: true });
      const ok = await verifyPersonPassword(project, claim.personId, String(b.password || ''));
      if (ok) clearLoginFailures(key); else recordLoginFailure(key);
      return send(res, 200, { ok });
    }

    // Levels, a project's people, console administrators (api/orgApi.mjs).
    if (await handleOrgApi({ req, res, method, path, admin, send, readJson })) return;

    // Acting as a business — the one way the platform owner opens the work (R5).
    if (await handleActAsApi({ req, res, method, path, admin, send, readJson })) return;

    // The record of who did what, and on whose behalf. Scope-filtered, so an
    // Operator's administrators read their own estate's trail and no further.
    if (path === '/api/audit' && method === 'GET') {
      const url = new URL(req.url, 'http://x');
      return send(res, 200, {
        events: await listAdminAudit(scope, {
          tenantSlug: url.searchParams.get('tenant'),
          limit: url.searchParams.get('limit'),
        }),
      });
    }

    if (path === '/api/health') {
      // Liveness is public; which projects are running is platform detail.
      const viewer = await currentAdmin(req);
      if (!viewer || !isPlatform(viewer.scope)) return send(res, 200, { ok: true });
      return send(res, 200, { ok: true, running: rt.listRunning() });
    }
    // Platform-wide configuration: platform administrators only.
    if (path === '/api/settings' || path === '/api/ai-guidance-default' || path === '/api/models') {
      requirePlatform(admin);
    }
    if (path === '/api/settings') {
      if (method === 'GET') return send(res, 200, await getSettings());
      if (method === 'POST') {
        const bodyIn = await readJson(req);
        await enforceToolCapability(bodyIn); // throws -> 400
        return send(res, 200, await saveSettings(bodyIn));
      }
    }
    if (path === '/api/ai-guidance-default') {
      // The global AI guidance file (/rules/globalAiGuidanceRule.md), edited from
      // the console. GET reads it; POST overwrites it (the AI Gateway serves the
      // fresh text to every tenant's next message).
      if (method === 'GET') return send(res, 200, { guidance: getDefaultGuidance() });
      if (method === 'POST') {
        const b = await readJson(req);
        return send(res, 200, { guidance: saveDefaultGuidance(b.guidance ?? '') });
      }
    }
    if (path === '/api/models') {
      // Model picker source for the console: the live OpenRouter catalogue,
      // fetched with the operator's key. Empty until a key is saved.
      if (method === 'GET') return send(res, 200, { models: await listOpenrouterModels() });
    }
    if (path === '/api/tenants') {
      if (method === 'GET') {
        const rows = await tenantsRepo.listTenants(scope);
        return send(res, 200, { tenants: rows.map(tenantView) });
      }
      if (method === 'POST') {
        const body = await readJson(req);
        // The Business a new project belongs to: one the administrator can
        // reach, or — for the Connector's token — its own "Connector sites".
        const business = viaConnector
          ? await connectorBusiness()
          : await getBusinessInScope(scope, body.businessId);
        if (!business) return send(res, 404, { error: 'Choose a business you manage.' });
        // Recorded with the owner address that was chosen: naming yourself the
        // owner of a new project is a way in, and one nobody could see before.
        recordAdminAction({
          admin,
          action: 'tenant.create',
          targetType: 'business',
          targetId: String(business.id),
          detail: { name: body.name ?? null, ownerEmail: body.ownerEmail ?? null, tier: body.tier ?? null, viaConnector },
          ip: req.socket?.remoteAddress ?? null,
        });
        return send(res, 200, await provisionTenant({
          name: body.name,
          ownerEmail: body.ownerEmail,
          cfProject: body.cfProject,
          customDomain: body.customDomain,
          tier: body.tier,
          // Only the Connector's own token marks a project as the Connector's.
          connectorManaged: viaConnector,
          businessId: business.id,
        }));
      }
    }
    // ---- Connector-managed targets ----------------------------------------
    // Sites the connector provisioned, with the credentials to reach them, so
    // the connector can enrol them without a restart. Deliberately NOT every
    // tenant: `connector_managed` is set only when the connector created the
    // site, so this can never widen to sites we create ourselves — which is the
    // exposure the target allowlist exists to prevent.
    //
    // Behind the connector's own bearer token. It returns live credentials, so
    // "loopback only" is not sufficient on its own: anything that can reach the
    // control plane port could otherwise read every managed tenant's login.
    if (path === '/api/connector/targets' && method === 'GET') {
      const expected = (process.env.MMS_CONNECTOR_MCP_TOKEN || '').trim();
      const presented = (req.headers.authorization || '').replace(/^Bearer\s+/i, '').trim();
      if (!expected || !tokenMatches(presented, expected)) {
        return send(res, 401, { error: 'unauthorized' });
      }
      // The Connector's machine view: every Connector-created project, by design.
      const rows = await tenantsRepo.listAllTenants();
      const targets = {};
      for (const t of rows) {
        if (!t.connector_managed || t.status !== 'active' || !t.port) continue;
        const email = t.connector_email || t.owner_email;
        const enc = t.connector_email ? t.connector_password_enc : t.owner_password_enc;
        if (!email || !enc) continue; // still provisioning, or no credential seeded
        let secret;
        try { secret = decrypt(enc); } catch { continue; }
        if (!secret) continue;
        targets[t.slug] = { url: `http://127.0.0.1:${t.port}`, email, secret };
      }
      return send(res, 200, { targets });
    }
    // ---- MCP agent keys (operator console) --------------------------------
    // Minting happens HERE, not in the tenant: the QuickJS sandbox has no
    // CSPRNG, and keeping every key in one registry means one revoke path.
    if (path === '/api/mcp/agents') {
      if (method === 'GET') {
        const tenant = new URL(req.url, 'http://x').searchParams.get('tenant');
        if (tenant && !(await tenantsRepo.getTenantInScope(scope, tenant))) {
          return send(res, 404, { error: 'not found' });
        }
        return send(res, 200, { agents: await mcpAgents.listAgentKeys(scope, tenant || null) });
      }
      if (method === 'POST') {
        const b = await readJson(req);
        if (!b.tenantSlug) throw new Error('tenantSlug is required');
        const forKey = await tenantsRepo.getTenantInScope(scope, String(b.tenantSlug));
        if (!forKey) {
          return send(res, 404, { error: 'not found' });
        }
        // Minting a key IS opening the work: the key it returns reads and
        // writes this project's content and design (R5, AC-A5.1).
        const keyGrant = await requireOpenWork(admin, forKey);
        const permissions = b.preset
          ? normalizePermissions(PERMISSION_PRESETS[b.preset])
          : normalizePermissions(b.permissions);
        if (permissions.length === 0) throw new Error('Grant at least one permission');
        const agent = await mcpAgents.createAgentKey({
          tenantSlug: b.tenantSlug,
          label: b.label,
          permissions,
          tables: normalizeTables(b.tables),
          expiresInDays: b.expiresInDays,
        });
        recordAdminAction({
          admin,
          actAs: actorPair(keyGrant, forKey.business_id),
          action: 'agent.key.mint',
          tenantSlug: forKey.slug,
          targetType: 'agent_key',
          targetId: agent.key_id ?? agent.keyId ?? null,
          detail: { label: agent.label ?? b.label ?? null, permissions, preset: b.preset ?? null },
          ip: req.socket?.remoteAddress ?? null,
        });
        // `token` is present exactly once, here.
        return send(res, 200, { agent, endpoint: `${config.gatewayOrigin}/mcp/${b.tenantSlug}` });
      }
    }
    if (path === '/api/mcp/presets' && method === 'GET') {
      return send(res, 200, { presets: PERMISSION_PRESETS });
    }
    if (path === '/api/mcp/directory' && method === 'GET') {
      const [tenants, counts] = await Promise.all([
        tenantsRepo.listTenants(scope),
        mcpAgents.agentKeyCounts(scope),
      ]);
      const byTenant = new Map(counts.map((c) => [c.tenant_slug, c]));
      // Listing keys no longer probes each project. The probe opened an OWNER
      // session inside every reachable tenant on every load of this page —
      // the platform owner reading the work by accident, which R5 forbids, and
      // an SSO round-trip per project besides. Whether the bridge is installed
      // is now what the last install recorded; the probe is a deliberate,
      // gated act (`?probe=<slug>` below).
      const rows = tenants.map((t) => {
        const c = byTenant.get(t.slug);
        return {
          slug: t.slug,
          status: t.status,
          endpoint: `${config.gatewayOrigin}/mcp/${t.slug}`,
          activeKeys: c ? Number(c.active) : 0,
          totalKeys: c ? Number(c.total) : 0,
          lastUsed: c ? c.last_used : null,
          bridgeInstalled: t.bridge_installed_at ? true : null,
          bridgeInstalledAt: t.bridge_installed_at ?? null,
        };
      });
      return send(res, 200, { tenants: rows });
    }
    if (path === '/api/mcp/audit' && method === 'GET') {
      const url = new URL(req.url, 'http://x');
      const tenant = url.searchParams.get('tenant');
      if (!tenant) throw new Error('tenant is required');
      if (!(await tenantsRepo.getTenantInScope(scope, tenant))) return send(res, 404, { error: 'not found' });
      return send(res, 200, { events: await mcpAgents.listAgentAudit(scope, tenant, url.searchParams.get('limit')) });
    }
    // Build the bridge package from source and install it into one tenant.
    // Zipping by hand and uploading through each tenant's admin UI does not
    // scale, so rollout is one call per site — and re-callable to upgrade.
    const mcpInstall = path.match(/^\/api\/mcp\/tenants\/([a-z0-9-]+)\/install-bridge$/);
    if (mcpInstall && method === 'POST') {
      const t = await tenantsRepo.getTenantInScope(scope, mcpInstall[1]);
      if (!t) return send(res, 404, { error: 'not found' });
      // Installing writes into the project's CMS over an owner session, so it
      // is opening the work by any honest reading of it (R5).
      const grant = await requireOpenWork(admin, t);
      const out = await installBridge(t.slug);
      await tenantsRepo.markBridgeInstalled(t.slug);
      recordAdminAction({
        admin,
        actAs: actorPair(grant, t.business_id),
        action: 'bridge.install',
        tenantSlug: t.slug,
        targetType: 'tenant',
        targetId: t.slug,
        ip: req.socket?.remoteAddress ?? null,
      });
      return send(res, 200, out);
    }
    // Ask ONE project whether its bridge is there. Deliberate, gated and
    // recorded, because the answer costs a session inside that project.
    const mcpProbe = path.match(/^\/api\/mcp\/tenants\/([a-z0-9-]+)\/probe-bridge$/);
    if (mcpProbe && method === 'POST') {
      const t = await tenantsRepo.getTenantInScope(scope, mcpProbe[1]);
      if (!t) return send(res, 404, { error: 'not found' });
      const grant = await requireOpenWork(admin, t);
      const installed = t.status === 'active' && t.port ? await pluginInstalled(t.slug).catch(() => false) : null;
      if (installed) await tenantsRepo.markBridgeInstalled(t.slug);
      recordAdminAction({
        admin,
        actAs: actorPair(grant, t.business_id),
        action: 'bridge.probe',
        tenantSlug: t.slug,
        targetType: 'tenant',
        targetId: t.slug,
        detail: { installed },
        ip: req.socket?.remoteAddress ?? null,
      });
      return send(res, 200, { slug: t.slug, bridgeInstalled: installed });
    }

    // Revoke only. A minted key is shown once, in the mint response, and can
    // never be read back (NEW-1): only its keyed hash is stored.
    const mcpKey = path.match(/^\/api\/mcp\/agents\/([A-Za-z0-9_-]+)\/revoke$/);
    if (mcpKey && method === 'POST') {
      const agent = await mcpAgents.revokeAgentKey(scope, mcpKey[1]);
      if (!agent) return send(res, 404, { error: 'key not found or already revoked' });
      return send(res, 200, { agent });
    }

    const m = path.match(/^\/api\/tenants\/([a-z0-9-]+)(?:\/(start|deploy|update|repair|expose))?$/);
    if (m) {
      // A project outside the administrator's scope does not exist, for reads
      // and changes alike (AC-A1.2).
      const tenant = await tenantsRepo.getTenantInScope(scope, m[1]);
      if (!tenant) return send(res, 404, { error: 'not found' });
      const slug = tenant.slug;
      const action = m[2];
      if (!action && method === 'DELETE') {
        const deleteCf = new URL(req.url, 'http://x').searchParams.get('cf') === '1';
        return send(res, 200, await deprovisionTenant(slug, { deleteCf }));
      }
      if (action === 'start' && method === 'POST') return send(res, 200, await startTenant(slug));
      if (action === 'deploy' && method === 'POST') return send(res, 200, await deployTenant(slug));
      if (action === 'update' && method === 'POST') return send(res, 200, await editTenant(slug, await readJson(req)));
      if (action === 'repair' && method === 'POST') return send(res, 200, await repairTenantCf(slug));
      if (action === 'expose' && method === 'POST') {
        // This points the PUBLIC funnel at a project's CMS with no session in
        // front of it — the widest way there is to open a business's work, and
        // it was one unlinked URL away. Gated and recorded like the rest.
        const grant = await requireOpenWork(admin, tenant);
        const out = await pointTestFunnel(slug);
        recordAdminAction({
          admin,
          actAs: actorPair(grant, tenant.business_id),
          action: 'tenant.expose',
          tenantSlug: slug,
          targetType: 'tenant',
          targetId: slug,
          ip: req.socket?.remoteAddress ?? null,
        });
        return send(res, 200, out);
      }
    }
    // An admin route no handler above claimed ends here. It must never fall
    // through to the tenant proxy below with an administrator's request.
    if (isAdminApiPath(path)) return send(res, 404, { error: 'not found' });

    // Tenant-triggered deploy: a tenant's Instatic instance calls this (with its
    // signed token) right after an explicit Publish. The control-plane runs the
    // Cloudflare deploy with the operator's token — the token never leaves here.
    // Kicked off in the BACKGROUND so the tenant's Publish returns immediately;
    // progress + result land in the deploys registry (visible in the console).
    const dm = path.match(/^\/deploy\/(.+)$/);
    if (dm && method === 'POST') {
      const slug = verifyTenantToken(decodeURIComponent(dm[1]));
      if (!slug) return send(res, 401, { error: 'invalid tenant token' });
      // The publish now says WHAT it published (R9). The call carried no body
      // at all before, which is why a deploy record could name a time and a URL
      // and nothing about the content. An older CMS sends nothing, and the
      // receipt then records the absence rather than inventing a hash.
      const published = await readJson(req).catch(() => ({}));
      deployTenant(slug, {
        publishedSiteHash: typeof published.siteHash === 'string' ? published.siteHash : null,
        publishedPages: Number.isFinite(published.publishedPages) ? published.publishedPages : null,
      }).catch((e) => console.error(`[deploy] ${slug} failed:`, e.message));
      return send(res, 202, { accepted: true, slug });
    }

    // Anything the control-plane didn't claim: reverse-proxy it to the right
    // backend — /od/<slug>/* to that tenant's OpenDesign, everything else to the
    // current hub session's Instatic (at root). Returns false if nothing matched.
    if (await handleGatewayProxy(req, res, method, path)) return;

    // A bare visit with no session lands on the tenant sign-in.
    if (method === 'GET' && path === '/') { res.writeHead(302, { location: '/login' }); return res.end(); }
    send(res, 404, { error: 'not found' });
  } catch (e) {
    console.error('[control-plane]', e.message);
    send(res, Number.isInteger(e.status) ? e.status : 400, { error: e.message });
  }
});

// WebSocket / upgrade passthrough so Next.js dev HMR and live editor bridges work
// through the gateway (best-effort; a failed upgrade just closes the socket).
server.on('upgrade', (req, socket, head) => {
  handleGatewayUpgrade(req, socket, head).catch(() => socket.destroy());
});

// --- resilience: a single tenant/child failure must never crash the whole
// control-plane. Without these guards an unhandled async error (e.g. a child
// process 'error' that slipped a listener) took the supervisor down mid-request,
// which is why provisioning intermittently killed the server. Log and stay up. ---
process.on('uncaughtException', (err) => {
  console.error('[control-plane] uncaughtException (kept alive):', err);
});
process.on('unhandledRejection', (err) => {
  console.error('[control-plane] unhandledRejection (kept alive):', err);
});

// --- boot ---
await migrate();
const resumed = await resumeAll();

// An act-as grant lasts an hour, and expiry has to be swept rather than merely
// checked when someone signs in: the products hold their own sessions, so a
// grant whose person row still exists is still an account they honour. Every
// five minutes, and once at startup, so a grant cannot outlive a restart.
const sweepGrants = async () => {
  try {
    const ended = await sweepExpiredGrants();
    for (const person of ended) {
      syncPeopleSoon(person.tenant_slug, 0);
      recordAdminAction({
        admin: { id: person.staff_admin_id, email: 'expired-grant', scope_level: 'platform' },
        actAs: { grantId: person.staff_grant_id, businessId: null },
        action: 'act_as.expired',
        tenantSlug: person.tenant_slug,
        targetType: 'tenant',
        targetId: person.tenant_slug,
      });
    }
    if (ended.length) console.log(`[act-as] ended ${ended.length} expired grant(s)`);
    sweepFailures = 0;
  } catch (e) {
    // This sweep is the ONLY thing that invalidates an expired grant — it is the
    // statement that sets `status='removed', password_hash=null`. The products
    // hold their own sessions, so a grant whose row survives is still an account
    // they honour. A swallowed failure here does not delay an expiry; it cancels
    // one, and an hour-scoped staff credential stays live for as long as the
    // fault lasts.
    //
    // One failure is a blip — the next tick is five minutes away and almost
    // always fixes it — so it stays a log line. A run of them is a stuck sweep,
    // and that goes into the audit record, which is the durable, operator-visible
    // place and is already append-only.
    sweepFailures += 1;
    console.error(`[act-as] expiry sweep failed (${sweepFailures} in a row):`, e.message);
    if (sweepFailures === SWEEP_ALERT_AFTER) {
      recordAdminAction({
        admin: { id: null, email: 'control-plane', scope_level: 'platform' },
        action: 'act_as.sweep.failing',
        targetType: 'platform',
        targetId: 'act-as-sweep',
        ok: false,
        error: e.message,
        detail: {
          consecutiveFailures: sweepFailures,
          since: new Date(Date.now() - sweepFailures * 5 * 60_000).toISOString(),
          consequence:
            'Expired act-as grants are NOT being revoked. Any staff impersonation that has ' +
            'passed its expiry is still a working account on the tenant until this succeeds.',
        },
      });
    }
  }
};
/** Consecutive sweep failures. Reset on the first success. */
let sweepFailures = 0;
/**
 * How many in a row before it is worth waking somebody.
 *
 * Three ticks is fifteen minutes — long enough that a restart or a brief
 * database blip has passed, short enough that a grant meant to last an hour has
 * not outlived its window by much.
 */
const SWEEP_ALERT_AFTER = 3;
await sweepGrants();
setInterval(sweepGrants, 5 * 60_000).unref();
server.listen(config.controlPlanePort, '127.0.0.1', async () => {
  console.log(`[control-plane] listening on ${config.publicBaseUrl}`);
  console.log(`[control-plane] resumed instances: ${resumed.length ? resumed.join(', ') : '(none)'}`);
  console.log(`[gateway] public entry  : ${config.gatewayOrigin}  (funnel :${config.gatewayPort} -> 127.0.0.1:${config.controlPlanePort})`);
  console.log(`[gateway] tenant sign-in: ${config.gatewayOrigin}/login`);
  console.log(`[gateway] operator      : ${config.gatewayOrigin}/operator   (admin sign-in required)`);
  // Open the funnel only now the gated server is up (never point it at ungated code).
  await openFunnel();
});

// The delivery board on the tailnet, and nothing else.
//
// The control plane itself stays on loopback and is the funnel's public
// upstream, so it does not serve the board at all. This is a separate listener
// bound to the tailnet address alone, serving one file.
const boardHost = tailnetAddress();
if (boardHost) {
  const boardPort = Number(process.env.BOARD_PORT || 4460);
  http
    .createServer(async (req, res) => {
      const p = new URL(req.url, 'http://x').pathname;
      if (p !== '/' && p !== '/board' && p !== '/board/') return send(res, 404, { error: 'Not found.' });
      return serveBoard(req, res, req.method);
    })
    .listen(boardPort, boardHost, () => {
      console.log(`[board] delivery board  : http://${boardHost}:${boardPort}/board   (tailnet only, read-only)`);
    })
    .on('error', (err) => console.error('[board] not served:', err.message));
} else {
  console.log('[board] no tailnet address on this machine; the board is served on loopback only');
}

// --- graceful shutdown: stop tenant instances so none are orphaned ---
function shutdown() {
  console.log('\n[control-plane] shutting down; stopping tenant instances...');
  closeFunnel().catch(() => {}); // take the public gateway down first
  for (const r of rt.listRunning()) rt.stop(r.slug);
  // Also stop each tenant's OpenDesign (daemon + Next web), or they orphan and
  // keep holding their ports — the next boot's resume would then fail to rebind.
  for (const r of odrt.listRunning()) odrt.stop(r.slug);
  setTimeout(() => process.exit(0), 1200);
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
