// SiteAgent control-plane HTTP API. Node built-ins + pg only.
// Wires Registry + Provisioner + Deployer + AI Gateway. The Astro console calls this.
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { networkInterfaces } from 'node:os';
import { dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './lib/env.mjs';
import { migrate } from './registry/db.mjs';
import { getSettings, saveSettings, getSecrets, getDefaultGuidance, saveDefaultGuidance } from './registry/settings.mjs';
import * as tenantsRepo from './registry/tenants.mjs';
import { provisionTenant, deprovisionTenant, startTenant, resumeAll, editTenant, repairTenantCf, pointTestFunnel, createTenantInvite } from './provisioner/provision.mjs';
import { deployTenant, hasBakedOutput } from './deployer/deploy.mjs';
import { handleGateway } from './ai-gateway/gateway.mjs';
import { verifyTenantToken, decrypt } from './lib/crypto.mjs';
import {
  currentAdmin, isAdminApiPath, connectorMayCall, tokenMatches, signAdminSession,
  loginLockedFor, recordLoginFailure, clearLoginFailures, ADMIN_SESSION_TTL_SEC,
} from './lib/adminAuth.mjs';
import { validateAdminLogin } from './registry/adminUsers.mjs';
import { decorate } from './lib/tenantView.mjs';
import * as rt from './runtime/tenantRuntime.mjs';
import * as odrt from './runtime/odRuntime.mjs';
import { handleHub } from './hub/hub.mjs';
import { handleMcpGateway } from './mcp/gateway.mjs';
import * as mcpAgents from './registry/mcpAgents.mjs';
import { normalizePermissions, normalizeTables, PERMISSION_PRESETS } from './mcp/permissions.mjs';
import { pluginInstalled } from './mcp/session.mjs';
import { installBridge } from './mcp/bridgeInstall.mjs';
import { serveMcpDocumentation } from './mcp/documentation.mjs';
import { handleGatewayProxy, handleGatewayUpgrade } from './gateway/proxy.mjs';
import { openFunnel, closeFunnel } from './gateway/funnel.mjs';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function send(res, code, obj) {
  res.writeHead(code, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store', ...CORS });
  res.end(JSON.stringify(obj));
}

// The delivery board, generated by `node docs/board/build-board.mjs`.
const BOARD_FILE = resolvePath(dirname(fileURLToPath(import.meta.url)), '../../docs/board/index.html');

/**
 * The board is read by the other party over the tailnet, so it is served with
 * no session — but only to a request that arrived on the tailnet interface. The
 * board names which security controls do not exist yet, which is precisely the
 * list that must not be reachable from the public address.
 *
 * Loopback does NOT count: the Tailscale funnel delivers public traffic to the
 * main server over 127.0.0.1, which is how the board used to be public at
 * <gateway>/board. It is now served only by the tailnet listener at the bottom
 * of this file.
 */
function onPrivateInterface(req) {
  const ip = (req.socket?.localAddress ?? '').replace(/^::ffff:/, '');
  const [a, b] = ip.split('.').map(Number);
  return a === 100 && b >= 64 && b <= 127; // Tailscale's CGNAT range
}

/** This machine's tailnet address, or null when it is not on one. */
function tailnetAddress() {
  for (const list of Object.values(networkInterfaces())) {
    for (const nic of list ?? []) {
      if (nic.family !== 'IPv4' || nic.internal) continue;
      const [a, b] = nic.address.split('.').map(Number);
      if (a === 100 && b >= 64 && b <= 127) return nic.address;
    }
  }
  return null;
}

async function serveBoard(req, res, method) {
  if (method !== 'GET' && method !== 'HEAD') return send(res, 405, { error: 'Use GET.' });
  if (!onPrivateInterface(req)) return send(res, 404, { error: 'Not found.' });
  try {
    const html = await readFile(BOARD_FILE, 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    return res.end(method === 'HEAD' ? undefined : html);
  } catch {
    return send(res, 503, { error: 'The board has not been generated: run node docs/board/build-board.mjs' });
  }
}

function readJson(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => { data += c; if (data.length > 1_000_000) req.destroy(); });
    req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { resolve({}); } });
    req.on('error', () => resolve({}));
  });
}

// A tenant row plus its live runtime status, for the console (lib/tenantView.mjs).
const tenantView = (row) => decorate(row, {
  running: rt.isRunning(row.slug),
  odRunning: odrt.isRunning(row.slug),
  published: hasBakedOutput(row.slug),
});

// The session is returned in the body, not as a Set-Cookie: the Astro console
// calls this server-side and sets `sa_admin` on its own /operator path.
async function adminLogin(req, res) {
  const b = await readJson(req);
  const email = String(b.email || '').trim().toLowerCase();
  const lockedMs = loginLockedFor(email);
  if (lockedMs) {
    return send(res, 429, {
      error: `Too many failed sign-ins. Try again in ${Math.ceil(lockedMs / 60_000)} minute(s).`,
      locked: true,
    });
  }
  const admin = await validateAdminLogin(email, String(b.password || ''));
  if (!admin) {
    recordLoginFailure(email);
    return send(res, 401, { error: 'Wrong email or password.' });
  }
  clearLoginFailures(email);
  return send(res, 200, {
    session: signAdminSession(admin),
    maxAgeSec: ADMIN_SESSION_TTL_SEC,
    email: admin.email,
  });
}

// Live OpenRouter model catalogue for the console picker, fetched with the
// operator's key. Returns [] until a key is saved (or on any upstream error) so
// the settings page still renders — it just shows no options yet.
async function listOpenrouterModels() {
  const { openrouterKey } = await getSecrets();
  if (!openrouterKey) return [];
  try {
    const r = await fetch('https://openrouter.ai/api/v1/models', {
      headers: { Authorization: `Bearer ${openrouterKey}` },
    });
    if (!r.ok) return [];
    const data = await r.json();
    return (data.data || [])
      .map((m) => ({
        id: m.id,
        name: m.name || m.id,
        // Tool-calling capability for the category picker (Codex #4). OpenRouter
        // lists it in supported_parameters; null = unknown metadata (UI warns
        // instead of hard-blocking). Routed chat categories need this true.
        toolCalling: Array.isArray(m.supported_parameters)
          ? m.supported_parameters.includes('tools')
          : null,
        // Image input capability. The CMS can route around a text-only model
        // (requiresVision -> the Design category), but MMS Design runs on ONE
        // model, so a text-only pick there means every tenant screenshot
        // attachment fails. null = unknown metadata (the picker keeps it).
        vision: m.architecture && Array.isArray(m.architecture.input_modalities)
          ? m.architecture.input_modalities.includes('image')
          : null,
      }))
      .sort((a, b) => a.id.localeCompare(b.id));
  } catch {
    return [];
  }
}

// Reject categories whose model is KNOWN to lack tool-calling (routed chat
// categories always send tools) — server-side enforcement (Codex R2-#1). Models
// with unknown capability are allowed (the UI warns). If the catalogue can't be
// loaded (no key / upstream down) we can't verify, so we don't block.
// Also covers the MMS Design model, which needs tool-calling even more than the
// CMS categories do: an OpenDesign run is one long tool loop, so a model without
// tools produces a session that talks but never builds anything.
async function enforceToolCapability({ aiCategories, designModel } = {}) {
  const needs = [];
  if (Array.isArray(aiCategories)) {
    for (const c of aiCategories) {
      if (c && typeof c === 'object' && c.modelId) {
        needs.push({ model: c.modelId, label: `category "${c.slug || c.name}"` });
      }
    }
  }
  if (typeof designModel === 'string' && designModel.trim()) {
    needs.push({ model: designModel.trim(), label: 'MMS Design' });
  }
  if (!needs.length) return;
  const models = await listOpenrouterModels();
  if (!models.length) return;
  const cap = new Map(models.map((m) => [m.id, m.toolCalling]));
  for (const n of needs) {
    if (cap.get(n.model) === false) {
      throw new Error(`model "${n.model}" for ${n.label} does not support tool calling`);
    }
  }
}

const server = http.createServer(async (req, res) => {
  const path = new URL(req.url, 'http://x').pathname;
  const method = req.method;

  if (method === 'OPTIONS') { res.writeHead(204, CORS); return res.end(); }

  // AI gateway (instances call this; the key never leaves the control plane)
  if (path.startsWith('/ai/')) return handleGateway(req, res, path.slice(4));

  try {
    // MCP gateway (external AI agents). Mounted ahead of the hub and the tenant
    // proxy: it authenticates with its own bearer key, not a hub session, so it
    // must never fall through to either.
    if (path.startsWith('/mcp/') && (await handleMcpGateway(req, res, method, path))) return;

    // MCP guide. Ahead of the gateway proxy, which would otherwise hand every
    // /operator/* path to the Astro console.
    if (await serveMcpDocumentation(req, res, method, path)) return;

    // Tenant Hub (login / invite / two-card home) — the HTML surface tenants use.
    if (await handleHub(req, res, method, path)) return;

    // No /board here: this server is the funnel's upstream, so it is public.
    // The board is served by the tailnet-only listener at the bottom.

    // R14: every admin/operator route requires a signed-in administrator. One
    // gate for all of them, ahead of every handler, so a route cannot forget
    // it (lib/adminAuth.selftest.mjs checks each /api/ route is covered).
    if (isAdminApiPath(path)) {
      if (!(await currentAdmin(req)) && !connectorMayCall(method, path, req)) {
        return send(res, 401, { error: 'admin sign-in required' });
      }
    }

    if (path === '/api/admin/login' && method === 'POST') return adminLogin(req, res);
    if (path === '/api/admin/session' && method === 'GET') {
      return send(res, 200, { admin: await currentAdmin(req) });
    }

    if (path === '/api/health') {
      // Liveness is public; which tenants are running is not.
      if (!(await currentAdmin(req))) return send(res, 200, { ok: true });
      return send(res, 200, { ok: true, running: rt.listRunning() });
    }
    if (path === '/api/settings') {
      if (method === 'GET') return send(res, 200, await getSettings());
      if (method === 'POST') {
        const bodyIn = await readJson(req);
        await enforceToolCapability(bodyIn); // throws -> 400
        return send(res, 200, await saveSettings(bodyIn));
      }
    }
    if (path === '/api/ai-guidance-default') {
      // The global AI guidance file (/rules/globalAiGuidanceRule.md), edited from
      // the console. GET reads it; POST overwrites it (the AI Gateway serves the
      // fresh text to every tenant's next message).
      if (method === 'GET') return send(res, 200, { guidance: getDefaultGuidance() });
      if (method === 'POST') {
        const b = await readJson(req);
        return send(res, 200, { guidance: saveDefaultGuidance(b.guidance ?? '') });
      }
    }
    if (path === '/api/models') {
      // Model picker source for the console: the live OpenRouter catalogue,
      // fetched with the operator's key. Empty until a key is saved.
      if (method === 'GET') return send(res, 200, { models: await listOpenrouterModels() });
    }
    if (path === '/api/tenants') {
      if (method === 'GET') {
        const rows = await tenantsRepo.listTenants();
        return send(res, 200, { tenants: rows.map(tenantView) });
      }
      if (method === 'POST') {
        const body = await readJson(req);
        return send(res, 200, await provisionTenant(body));
      }
    }
    // ---- Connector-managed targets ----------------------------------------
    // Sites the connector provisioned, with the credentials to reach them, so
    // the connector can enrol them without a restart. Deliberately NOT every
    // tenant: `connector_managed` is set only when the connector created the
    // site, so this can never widen to sites we create ourselves — which is the
    // exposure the target allowlist exists to prevent.
    //
    // Behind the connector's own bearer token. It returns live credentials, so
    // "loopback only" is not sufficient on its own: anything that can reach the
    // control plane port could otherwise read every managed tenant's login.
    if (path === '/api/connector/targets' && method === 'GET') {
      const expected = (process.env.MMS_CONNECTOR_MCP_TOKEN || '').trim();
      const presented = (req.headers.authorization || '').replace(/^Bearer\s+/i, '').trim();
      if (!expected || !tokenMatches(presented, expected)) {
        return send(res, 401, { error: 'unauthorized' });
      }
      const rows = await tenantsRepo.listTenants();
      const targets = {};
      for (const t of rows) {
        if (!t.connector_managed || t.status !== 'active' || !t.port) continue;
        const email = t.connector_email || t.owner_email;
        const enc = t.connector_email ? t.connector_password_enc : t.owner_password_enc;
        if (!email || !enc) continue; // still provisioning, or no credential seeded
        let secret;
        try { secret = decrypt(enc); } catch { continue; }
        if (!secret) continue;
        targets[t.slug] = { url: `http://127.0.0.1:${t.port}`, email, secret };
      }
      return send(res, 200, { targets });
    }
    // ---- MCP agent keys (operator console) --------------------------------
    // Minting happens HERE, not in the tenant: the QuickJS sandbox has no
    // CSPRNG, and keeping every key in one registry means one revoke path.
    if (path === '/api/mcp/agents') {
      if (method === 'GET') {
        const tenant = new URL(req.url, 'http://x').searchParams.get('tenant');
        return send(res, 200, { agents: await mcpAgents.listAgentKeys(tenant || null) });
      }
      if (method === 'POST') {
        const b = await readJson(req);
        if (!b.tenantSlug) throw new Error('tenantSlug is required');
        const permissions = b.preset
          ? normalizePermissions(PERMISSION_PRESETS[b.preset])
          : normalizePermissions(b.permissions);
        if (permissions.length === 0) throw new Error('Grant at least one permission');
        const agent = await mcpAgents.createAgentKey({
          tenantSlug: b.tenantSlug,
          label: b.label,
          permissions,
          tables: normalizeTables(b.tables),
          expiresInDays: b.expiresInDays,
        });
        // `token` is present exactly once, here.
        return send(res, 200, { agent, endpoint: `${config.gatewayOrigin}/mcp/${b.tenantSlug}` });
      }
    }
    if (path === '/api/mcp/presets' && method === 'GET') {
      return send(res, 200, { presets: PERMISSION_PRESETS });
    }
    if (path === '/api/mcp/directory' && method === 'GET') {
      const [tenants, counts] = await Promise.all([
        tenantsRepo.listTenants(),
        mcpAgents.agentKeyCounts(),
      ]);
      const byTenant = new Map(counts.map((c) => [c.tenant_slug, c]));
      const rows = await Promise.all(
        tenants.map(async (t) => {
          const c = byTenant.get(t.slug);
          // Probing costs an SSO round-trip per tenant, so only ask a tenant
          // that could actually answer. A stopped or unprovisioned one reports
          // `null` (unknown) rather than a misleading "not installed".
          const reachable = t.status === 'active' && !!t.port;
          return {
            slug: t.slug,
            status: t.status,
            endpoint: `${config.gatewayOrigin}/mcp/${t.slug}`,
            activeKeys: c ? Number(c.active) : 0,
            totalKeys: c ? Number(c.total) : 0,
            lastUsed: c ? c.last_used : null,
            bridgeInstalled: reachable ? await pluginInstalled(t.slug).catch(() => false) : null,
          };
        }),
      );
      return send(res, 200, { tenants: rows });
    }
    if (path === '/api/mcp/audit' && method === 'GET') {
      const url = new URL(req.url, 'http://x');
      const tenant = url.searchParams.get('tenant');
      if (!tenant) throw new Error('tenant is required');
      return send(res, 200, { events: await mcpAgents.listAgentAudit(tenant, url.searchParams.get('limit')) });
    }
    // Build the bridge package from source and install it into one tenant.
    // Zipping by hand and uploading through each tenant's admin UI does not
    // scale, so rollout is one call per site — and re-callable to upgrade.
    const mcpInstall = path.match(/^\/api\/mcp\/tenants\/([a-z0-9-]+)\/install-bridge$/);
    if (mcpInstall && method === 'POST') {
      return send(res, 200, await installBridge(mcpInstall[1]));
    }

    // Revoke only. A minted key is shown once, in the mint response, and can
    // never be read back (NEW-1): only its keyed hash is stored.
    const mcpKey = path.match(/^\/api\/mcp\/agents\/([A-Za-z0-9_-]+)\/revoke$/);
    if (mcpKey && method === 'POST') {
      const agent = await mcpAgents.revokeAgentKey(mcpKey[1]);
      if (!agent) return send(res, 404, { error: 'key not found or already revoked' });
      return send(res, 200, { agent });
    }

    const m = path.match(/^\/api\/tenants\/([a-z0-9-]+)(?:\/(start|deploy|update|repair|expose|invite))?$/);
    if (m) {
      const slug = m[1];
      const action = m[2];
      if (!action && method === 'DELETE') {
        const deleteCf = new URL(req.url, 'http://x').searchParams.get('cf') === '1';
        return send(res, 200, await deprovisionTenant(slug, { deleteCf }));
      }
      if (action === 'start' && method === 'POST') return send(res, 200, await startTenant(slug));
      if (action === 'deploy' && method === 'POST') return send(res, 200, await deployTenant(slug));
      if (action === 'update' && method === 'POST') return send(res, 200, await editTenant(slug, await readJson(req)));
      if (action === 'invite' && method === 'POST') return send(res, 200, await createTenantInvite(slug));
      if (action === 'repair' && method === 'POST') return send(res, 200, await repairTenantCf(slug));
      if (action === 'expose' && method === 'POST') return send(res, 200, await pointTestFunnel(slug));
    }
    // Tenant-triggered deploy: a tenant's Instatic instance calls this (with its
    // signed token) right after an explicit Publish. The control-plane runs the
    // Cloudflare deploy with the operator's token — the token never leaves here.
    // Kicked off in the BACKGROUND so the tenant's Publish returns immediately;
    // progress + result land in the deploys registry (visible in the console).
    const dm = path.match(/^\/deploy\/(.+)$/);
    if (dm && method === 'POST') {
      const slug = verifyTenantToken(decodeURIComponent(dm[1]));
      if (!slug) return send(res, 401, { error: 'invalid tenant token' });
      deployTenant(slug).catch((e) => console.error(`[deploy] ${slug} failed:`, e.message));
      return send(res, 202, { accepted: true, slug });
    }

    // Anything the control-plane didn't claim: reverse-proxy it to the right
    // backend — /od/<slug>/* to that tenant's OpenDesign, everything else to the
    // current hub session's Instatic (at root). Returns false if nothing matched.
    if (await handleGatewayProxy(req, res, method, path)) return;

    // A bare visit with no session lands on the tenant sign-in.
    if (method === 'GET' && path === '/') { res.writeHead(302, { location: '/login' }); return res.end(); }
    send(res, 404, { error: 'not found' });
  } catch (e) {
    console.error('[control-plane]', e.message);
    send(res, 400, { error: e.message });
  }
});

// WebSocket / upgrade passthrough so Next.js dev HMR and live editor bridges work
// through the gateway (best-effort; a failed upgrade just closes the socket).
server.on('upgrade', (req, socket, head) => {
  handleGatewayUpgrade(req, socket, head).catch(() => socket.destroy());
});

// --- resilience: a single tenant/child failure must never crash the whole
// control-plane. Without these guards an unhandled async error (e.g. a child
// process 'error' that slipped a listener) took the supervisor down mid-request,
// which is why provisioning intermittently killed the server. Log and stay up. ---
process.on('uncaughtException', (err) => {
  console.error('[control-plane] uncaughtException (kept alive):', err);
});
process.on('unhandledRejection', (err) => {
  console.error('[control-plane] unhandledRejection (kept alive):', err);
});

// --- boot ---
await migrate();
const resumed = await resumeAll();
server.listen(config.controlPlanePort, '127.0.0.1', async () => {
  console.log(`[control-plane] listening on ${config.publicBaseUrl}`);
  console.log(`[control-plane] resumed instances: ${resumed.length ? resumed.join(', ') : '(none)'}`);
  console.log(`[gateway] public entry  : ${config.gatewayOrigin}  (funnel :${config.gatewayPort} -> 127.0.0.1:${config.controlPlanePort})`);
  console.log(`[gateway] tenant sign-in: ${config.gatewayOrigin}/login`);
  console.log(`[gateway] operator      : ${config.gatewayOrigin}/operator   (admin sign-in required)`);
  // Open the funnel only now the gated server is up (never point it at ungated code).
  await openFunnel();
});

// The delivery board on the tailnet, and nothing else.
//
// The control plane itself stays on loopback and is the funnel's public
// upstream, so it does not serve the board at all. This is a separate listener
// bound to the tailnet address alone, serving one file.
const boardHost = tailnetAddress();
if (boardHost) {
  const boardPort = Number(process.env.BOARD_PORT || 4460);
  http
    .createServer(async (req, res) => {
      const p = new URL(req.url, 'http://x').pathname;
      if (p !== '/' && p !== '/board' && p !== '/board/') return send(res, 404, { error: 'Not found.' });
      return serveBoard(req, res, req.method);
    })
    .listen(boardPort, boardHost, () => {
      console.log(`[board] delivery board  : http://${boardHost}:${boardPort}/board   (tailnet only, read-only)`);
    })
    .on('error', (err) => console.error('[board] not served:', err.message));
} else {
  console.log('[board] no tailnet address on this machine; the board is served on loopback only');
}

// --- graceful shutdown: stop tenant instances so none are orphaned ---
function shutdown() {
  console.log('\n[control-plane] shutting down; stopping tenant instances...');
  closeFunnel().catch(() => {}); // take the public gateway down first
  for (const r of rt.listRunning()) rt.stop(r.slug);
  // Also stop each tenant's OpenDesign (daemon + Next web), or they orphan and
  // keep holding their ports — the next boot's resume would then fail to rebind.
  for (const r of odrt.listRunning()) odrt.stop(r.slug);
  setTimeout(() => process.exit(0), 1200);
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
